# Generated by Django 2.2.6 on 2021-11-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(max_length=200)),
                ('dong', models.CharField(max_length=200)),
                ('sell', models.IntegerField(default=0)),
                ('size', models.FloatField(default=0.0)),
                ('floor', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('cstr_date', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
