# Generated by Django 2.2.6 on 2021-11-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_price', '0002_dong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(max_length=200)),
                ('dong', models.CharField(max_length=200)),
                ('sell', models.IntegerField(default=0)),
                ('size', models.FloatField(default=0.0)),
                ('floor', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('cstr_year', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('built_year', models.IntegerField(default=0)),
                ('brand_score', models.IntegerField(default=0)),
                ('trade_index', models.FloatField(default=0.0)),
            ],
        ),
    ]
